# Generated by Django 3.2.4 on 2021-07-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('desripation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=4)),
                ('parentCategory', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_size',
            name='sub_category',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Stock_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField(default=0)),
                ('sub_category', models.IntegerField(default=0)),
                ('desripation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=4)),
                ('amount', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.product_size')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_size',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category'),
            preserve_default=False,
        ),
    ]
