# Generated by Django 3.2.4 on 2021-07-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_grocery_app', '0002_auto_20210705_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='goods_type',
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_detail',
            name='subcategory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subcategory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment_detail',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment_detail',
            name='subcategory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='online_grocery_app.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='subcategory',
            field=models.IntegerField(default=0),
        ),
    ]
