# Generated by Django 3.2.4 on 2021-07-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_grocery_app', '0003_auto_20210705_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='CustomerId',
            new_name='Customer',
        ),
    ]
