# Generated by Django 3.2.4 on 2021-07-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_grocery_app', '0004_rename_customerid_cart_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cartId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartlist', to='online_grocery_app.cart'),
        ),
    ]
