# Generated by Django 3.2.4 on 2021-07-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_grocery_app', '0005_alter_cartitem_cartid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartId',
            new_name='cart',
        ),
    ]
