# Generated by Django 3.2.4 on 2021-07-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_grocery_app', '0009_auto_20210722_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_detail',
            old_name='user_id',
            new_name='user',
        ),
    ]
